Ext.define('Checkgit.checkgit.shared.checkgit.model.appbasicsetup.usermanagement.SessionDataModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "dataId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "customerId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "sessionKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dataType",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "numberValue",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "dateTimeValue",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "stringValue",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "booleanValue",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "jsonValue",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "appSessionId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});