Ext.define('Checkgit.checkgit.shared.checkgit.model.appbasicsetup.usermanagement.UserDataModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "userDataId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "password",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "oneTimePassword",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "oneTimePasswordExpiry",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "oneTimePasswordGenDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "last5Passwords",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "User",
          "reference": "UserModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});