Ext.define('Lastgitcheck.lastgitcheck.shared.lastgitcheck.model.appbasicsetup.usermanagement.PasswordAlgoModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "algoId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "algorithm",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "algoName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "algoDescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "algoIcon",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "algoHelp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});