Ext.define('Lastgitcheck.lastgitcheck.shared.lastgitcheck.model.organization.locationmanagement.StateModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "stateId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "countryid",
          "reference": "Country",
          "defaultValue": ""
     }, {
          "name": "stateName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateCode",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "stateCodeChar2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateCodeChar3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateDescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateFlag",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateCapital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "stateCapitalLatitude",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "stateCapitalLongitude",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});